import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonSpinner, IonTitle, IonToolbar, ToastController } from '@ionic/angular';
import { addIcons } from 'ionicons';
import { arrowBackOutline, cloudUploadOutline, homeOutline, phonePortraitOutline } from 'ionicons/icons';
import { ContactCandidate, CustomerImportRow, normalizePhoneInput, parseVCard } from '../../core/customer-tools';
import { CustomersService } from '../../core/services/customers.service';

@Component({
  selector:'app-contact-import',
  imports:[CommonModule,FormsModule,IonHeader,IonToolbar,IonButtons,IonButton,IonIcon,IonTitle,IonContent,IonSpinner],
  template:`
    <ion-header><ion-toolbar><ion-buttons slot="start"><ion-button (click)="back()"><ion-icon slot="icon-only" name="arrow-back-outline" /></ion-button><ion-button (click)="home()"><ion-icon slot="icon-only" name="home-outline" /></ion-button></ion-buttons><ion-title>Nhập danh bạ</ion-title></ion-toolbar></ion-header>
    <ion-content><div class="shell"><section class="hero"><ion-icon name="phone-portrait-outline" /><h1>Chọn liên hệ cần nhập</h1><p>Trình duyệt không được tự đọc toàn bộ danh bạ. Bạn luôn chọn và xác nhận liên hệ trước khi dữ liệu được lưu.</p><button (click)="pickContacts()" [disabled]="busy()||!pickerSupported"><ion-icon name="phone-portrait-outline" /> CHỌN TỪ THIẾT BỊ</button>@if(!pickerSupported){<small>Thiết bị/trình duyệt này không hỗ trợ Contact Picker. Hãy dùng file vCard bên dưới.</small>}<label><ion-icon name="cloud-upload-outline" /> CHỌN FILE DANH BẠ (.VCF)<input type="file" accept=".vcf,text/vcard,text/x-vcard" (change)="pickVcard($event)" /></label></section>
      @if(contacts().length){<section class="card"><div class="head"><div><h2>Xem trước</h2><p>Chỉ những liên hệ được đánh dấu mới được nhập. Nếu có nhiều SĐT, hãy chọn số chính.</p></div><button (click)="toggleAll()">{{allSelected()?'Bỏ chọn':'Chọn tất cả'}}</button></div><div class="contacts">@for(contact of contacts();track $index){<article><input type="checkbox" [(ngModel)]="contact.selected" /><div><input class="name" [(ngModel)]="contact.name" aria-label="Tên liên hệ" />@if((contact.phones?.length||0)>1){<select [(ngModel)]="contact.phone" aria-label="Chọn số điện thoại chính">@for(phone of contact.phones;track phone){<option [value]="phone">{{phone}}</option>}</select>}@else{<span>{{contact.phone||'Không có SĐT'}} @if(contact.email){· {{contact.email}}}</span>}</div></article>}</div><label class="strategy">Khi trùng SĐT hoặc Email<select [(ngModel)]="strategy"><option value="skip">Bỏ qua</option><option value="update">Cập nhật khách hiện có</option></select></label><button class="import" (click)="confirmImport()" [disabled]="busy()||!selectedCount()">@if(busy()){<ion-spinner name="crescent" />} NHẬP {{selectedCount()}} LIÊN HỆ ĐÃ CHỌN</button></section>}
    </div></ion-content>
  `,
  styles:[`
    ion-content{--background:#f5f7fb}.shell{max-width:760px;margin:auto;padding:16px}.hero,.card{background:white;border:1px solid #e6e7ef;border-radius:16px;padding:20px;box-shadow:0 4px 18px rgba(34,28,70,.05);margin-bottom:14px}.hero{text-align:center}.hero>ion-icon{font-size:54px;color:#6030ff}.hero h1{font-size:20px;margin:9px 0}.hero p{color:#71768a;line-height:1.5}.hero button,.hero label,.import{min-height:46px;border-radius:10px;display:flex;align-items:center;justify-content:center;gap:8px;font-weight:800}.hero button{width:100%;border:0;background:#6030ff;color:white}.hero button:disabled{opacity:.45}.hero label{margin-top:10px;border:1px solid #42b9ad;color:#278f86;cursor:pointer}.hero label input{display:none}.hero small{display:block;color:#b45309;margin-top:8px}.head{display:flex;justify-content:space-between;gap:12px}.head h2{margin:0;font-size:17px}.head p{margin:4px 0;color:#777b8c;font-size:12px}.head button{border:0;background:#f1efff;color:#6030ff;border-radius:8px}.contacts{max-height:420px;overflow:auto;margin:12px 0}.contacts article{display:grid;grid-template-columns:auto 1fr;gap:10px;align-items:center;border-bottom:1px solid #eee;padding:10px 3px}.contacts article>div{display:flex;flex-direction:column;gap:3px}.contacts .name{border:0;font-weight:750;font-size:14px;color:#20243d}.contacts span{font-size:12px;color:#73778b}.strategy{display:flex;justify-content:space-between;align-items:center;font-size:12px;font-weight:700}.strategy select{height:38px;border:1px solid #ddd;border-radius:8px}.import{width:100%;border:0;background:#6030ff;color:white;margin-top:13px}.import:disabled{opacity:.45}
  `]
})
export class ContactImportPage{
  private readonly customers=inject(CustomersService);private readonly router=inject(Router);private readonly toasts=inject(ToastController);
  readonly contacts=signal<ContactCandidate[]>([]);readonly busy=signal(false);strategy:'skip'|'update'='skip';readonly pickerSupported=!!(navigator as any).contacts?.select;readonly selectedCount=computed(()=>this.contacts().filter(contact=>contact.selected&&contact.name.trim().length>=2).length);readonly allSelected=computed(()=>!!this.contacts().length&&this.contacts().every(contact=>contact.selected));
  constructor(){addIcons({arrowBackOutline,homeOutline,phonePortraitOutline,cloudUploadOutline});}
  back(){void this.router.navigateByUrl('/contact');}home(){void this.router.navigateByUrl('/home');}toggleAll(){const value=!this.allSelected();this.contacts.update(rows=>rows.map(row=>({...row,selected:value})));}
  async pickContacts(){if(!this.pickerSupported)return;try{const picked=await (navigator as any).contacts.select(['name','tel','email'],{multiple:true});this.contacts.set((picked??[]).map((item:any)=>{const phones=(item.tel??[]).map(normalizePhoneInput).filter(Boolean);return {name:String(item.name?.[0]??'').trim(),phone:phones[0]||undefined,phones,email:String(item.email?.[0]??'').trim().toLowerCase()||undefined,selected:true};}).filter((item:ContactCandidate)=>item.name&&!!(item.phone||item.email)));}catch(error:any){if(error?.name!=='AbortError')await this.toast('Không đọc được liên hệ đã chọn.','danger');}}
  async pickVcard(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;if(file.size>5*1024*1024){await this.toast('File vCard vượt quá 5 MB.','danger');return;}try{const rows=parseVCard(await file.text());this.contacts.set(rows);if(!rows.length)await this.toast('Không tìm thấy liên hệ hợp lệ trong file.','warning');}catch{await this.toast('File vCard không hợp lệ.','danger');}}
  async confirmImport(){const chosen=this.contacts().filter(contact=>contact.selected&&contact.name.trim().length>=2);if(!chosen.length)return;this.busy.set(true);try{const rows:CustomerImportRow[]=chosen.map((contact,index)=>({rowNumber:index+1,name:contact.name.trim(),phone:contact.phone,email:contact.email}));const result=await this.customers.importBatch(rows,this.strategy,crypto.randomUUID(),'Danh bạ thiết bị');await this.toast(`Đã tạo ${result.created}, cập nhật ${result.updated}, bỏ qua ${result.skipped}.`);this.contacts.set([]);}catch(error:any){await this.toast(error?.message??'Nhập danh bạ thất bại. Hãy chạy migration v33.','danger');}finally{this.busy.set(false);}}
  private async toast(message:string,color='success'){const toast=await this.toasts.create({message,color,duration:2600,position:'bottom'});await toast.present();}
}
