import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonSpinner, IonTitle, IonToolbar, ToastController } from '@ionic/angular';
import { addIcons } from 'ionicons';
import { arrowBackOutline, downloadOutline, homeOutline } from 'ionicons/icons';
import { Customer } from '../../core/models/models';
import { CustomersService } from '../../core/services/customers.service';
import { ExcelCell, ExcelIoService } from '../../core/services/excel-io.service';

interface ExportColumn { key: keyof Customer | 'group'; label: string; selected: boolean; }
@Component({
  selector:'app-customer-export',
  imports:[CommonModule,FormsModule,IonHeader,IonToolbar,IonButtons,IonButton,IonIcon,IonTitle,IonContent,IonSpinner],
  template:`
    <ion-header><ion-toolbar><ion-buttons slot="start"><ion-button (click)="back()" aria-label="Quay lại danh sách khách hàng"><ion-icon slot="icon-only" name="arrow-back-outline" /></ion-button><ion-button (click)="home()" aria-label="Về trang chủ"><ion-icon slot="icon-only" name="home-outline" /></ion-button></ion-buttons><ion-title>Xuất khách hàng ra Excel</ion-title></ion-toolbar></ion-header>
    <ion-content><div class="export-shell"><section class="card"><h2>Phạm vi xuất</h2><div class="scope-grid"><label><input type="radio" name="scope" value="all" [(ngModel)]="scope" /> Tất cả khách hàng được phép xem</label><label><input type="radio" name="scope" value="filtered" [(ngModel)]="scope" /> Theo bộ lọc bên dưới</label>@if(selectedIds.length){<label><input type="radio" name="scope" value="selected" [(ngModel)]="scope" /> {{selectedIds.length}} dòng đã chọn từ danh sách</label>}</div><div class="filters" [class.disabled]="scope!=='filtered'"><input [(ngModel)]="search" placeholder="Tên, SĐT, mã khách hàng" [disabled]="scope!=='filtered'" /><select [(ngModel)]="status" [disabled]="scope!=='filtered'" aria-label="Trạng thái khách hàng"><option value="">Mọi trạng thái</option><option value="lead">Tiềm năng</option><option value="active">Hoạt động</option><option value="inactive">Ngừng hoạt động</option></select><label class="debt"><input type="checkbox" [(ngModel)]="hasDebt" [disabled]="scope!=='filtered'" /> Chỉ khách còn nợ</label></div></section>
      <section class="card"><div class="heading"><div><h2>Chọn cột và thứ tự</h2><p>Điện thoại được xuất dạng văn bản để giữ số 0 đầu. Dữ liệu bắt đầu bằng công thức sẽ được vô hiệu hóa.</p></div><button (click)="selectAll()">Chọn tất cả</button></div><div class="columns">@for(column of columns;track column.key;let i=$index){<div><input type="checkbox" [(ngModel)]="column.selected" [attr.aria-label]="'Xuất cột ' + column.label" /><span>{{column.label}}</span><button (click)="move(i,-1)" [disabled]="i===0" [attr.aria-label]="'Di chuyển cột ' + column.label + ' lên'">↑</button><button (click)="move(i,1)" [disabled]="i===columns.length-1" [attr.aria-label]="'Di chuyển cột ' + column.label + ' xuống'">↓</button></div>}</div></section>
      <section class="card options"><label>Tên file<input [(ngModel)]="filename" /></label><label>Tên sheet<input [(ngModel)]="sheetName" maxlength="31" /></label></section>
      <button class="export" (click)="run()" [disabled]="busy()||!hasColumns()">@if(busy()){<ion-spinner name="crescent" />}@else{<ion-icon name="download-outline" />} {{busy()?'Đang chuẩn bị dữ liệu…':'XUẤT FILE EXCEL'}}</button>
      @if(lastCount()!==null){<p class="done" role="status" aria-live="polite">Đã xuất {{lastCount()}} dòng. Phạm vi xuất áp dụng trên toàn bộ dữ liệu phù hợp, không chỉ trang đang xem.</p>}
    </div></ion-content>
  `,
  styles:[`
    ion-content{--background:#f5f7fb}.export-shell{max-width:880px;margin:auto;padding:16px}.card{background:white;border:1px solid #e7e8ef;border-radius:15px;padding:18px;margin-bottom:13px;box-shadow:0 3px 16px rgba(35,29,70,.05)}h2{font-size:17px;margin:0 0 12px}p{font-size:12px;color:#73778b}.scope-grid{display:grid;gap:9px}.scope-grid label,.debt{display:flex;align-items:center;gap:8px}.filters{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:10px;margin-top:14px}.filters.disabled{opacity:.55}.filters>input,.filters select,.options input{height:42px;border:1px solid #dfe1e9;border-radius:9px;padding:0 10px}.heading{display:flex;justify-content:space-between;gap:14px}.heading h2{margin-bottom:3px}.heading button,.columns button{border:1px solid #ddd;border-radius:7px;background:white;color:#6030ff}.columns{display:grid;grid-template-columns:1fr 1fr;gap:7px}.columns>div{display:grid;grid-template-columns:auto 1fr 30px 30px;gap:7px;align-items:center;padding:9px;border:1px solid #eee;border-radius:9px}.options{display:grid;grid-template-columns:1fr 1fr;gap:12px}.options label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:700}.export{width:100%;height:48px;border:0;border-radius:11px;background:#6030ff;color:#fff;font-weight:850;display:flex;align-items:center;justify-content:center;gap:8px}.export:disabled{opacity:.45}.done{text-align:center;background:#eaf8ef;color:#17643b;padding:10px;border-radius:9px}@media(max-width:650px){.filters,.options,.columns{grid-template-columns:1fr}.heading{flex-direction:column}}
    .heading p{color:#64687b}
  `]
})
export class CustomerExportPage{
  private readonly customers=inject(CustomersService);private readonly excel=inject(ExcelIoService);private readonly router=inject(Router);private readonly route=inject(ActivatedRoute);private readonly toasts=inject(ToastController);
  readonly busy=signal(false);readonly lastCount=signal<number|null>(null);selectedIds:string[]=[];scope:'all'|'filtered'|'selected'='all';search='';status='';hasDebt=false;filename=`khach-hang-${new Date().toISOString().slice(0,10)}`;sheetName='Khách hàng';
  columns:ExportColumn[]=[{key:'code',label:'Mã KH',selected:true},{key:'name',label:'Họ tên',selected:true},{key:'phone',label:'Điện thoại',selected:true},{key:'email',label:'Email',selected:true},{key:'address',label:'Địa chỉ',selected:true},{key:'gender',label:'Giới tính',selected:true},{key:'dob',label:'Ngày sinh',selected:true},{key:'debt',label:'Công nợ',selected:true},{key:'total_spending',label:'Tổng chi tiêu',selected:true},{key:'status',label:'Trạng thái',selected:true},{key:'created_at',label:'Ngày tạo',selected:true}];
  constructor(){addIcons({arrowBackOutline,homeOutline,downloadOutline});this.selectedIds=(this.route.snapshot.queryParamMap.get('ids')??'').split(',').filter(Boolean);if(this.selectedIds.length)this.scope='selected';}
  back(){void this.router.navigateByUrl('/contact');}home(){void this.router.navigateByUrl('/home');}hasColumns(){return this.columns.some(column=>column.selected);}selectAll(){for(const column of this.columns)column.selected=true;}move(index:number,direction:number){const target=index+direction;if(target<0||target>=this.columns.length)return;[this.columns[index],this.columns[target]]=[this.columns[target],this.columns[index]];}
  async run(){this.busy.set(true);try{const filters=this.scope==='filtered'?{q:this.search,status:this.status||null,debtMin:this.hasDebt?0.000001:null}:{};let rows=await this.customers.listAll(filters);if(this.scope==='selected')rows=rows.filter(row=>this.selectedIds.includes(row.id));const selected=this.columns.filter(column=>column.selected);const body:ExcelCell[][]=rows.map(customer=>selected.map(column=>this.cell(customer,column.key)));this.excel.download(this.filename.trim()||'khach-hang',this.sheetName.trim()||'Khách hàng',[selected.map(column=>column.label),...body]);this.lastCount.set(rows.length);if(!rows.length)await this.toast('Không có dữ liệu phù hợp để xuất.','warning');}catch(error:any){await this.toast(error?.message??'Xuất dữ liệu thất bại.','danger');}finally{this.busy.set(false);}}
  cell(customer:Customer,key:ExportColumn['key']):ExcelCell{if(key==='group')return customer.customer_group_name??'';const value=customer[key];if(key==='phone')return value?String(value):'';if(key==='created_at'||key==='updated_at'||key==='dob')return value?String(value):'';if(key==='status')return ({lead:'Tiềm năng',active:'Hoạt động',inactive:'Ngừng hoạt động'} as any)[value as any]??'';return (value as ExcelCell)??'';}
  private async toast(message:string,color:string){const toast=await this.toasts.create({message,color,duration:2500,position:'bottom'});await toast.present();}
}
